# Searching Arrays 

You can search an array for a certain value and return the indexes that get a match. 

In [1]:
import numpy as np 

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


It returns the array index where the key element is present in the given array index. for example: array value 4 is present in the index number 3, 4, 5. 

In [2]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

x = np.where(arr % 2 == 0)

print(x)

(array([1, 3, 5, 7, 9], dtype=int64),)


At the array index [1, 3, 5, 7, 9] it matches with the arr[even number], arr[2, 4, 6, 8, 10]

In [3]:
x = np.where(arr % 2 == 1)

print(x)

(array([0, 2, 4, 6, 8], dtype=int64),)


At the array index [0, 2, 4, 6, 8]. It matches with the arr[odd number] are arr[1, 3, 5, 7, 9]

# Search Sorted Method
This method is used in the sorted arrays. 

There is searchsorted() method which performs binary search in the array, and returns the index where the
key is given to argument in the searchsorted function. 

In [4]:
arr = np.array([6, 7, 9, 11, 13])

x = np.searchsorted(arr, 9)

print(x)

2


It will return the array index number where the key has matched. In above code in the index number 2 the key 9 has matched which is true. 

In [8]:
# Find the indexes where the value 7 should be inserted, starting from the right. 

arr = np.array([6, 7, 8, 9, 10, 11])

x = np.searchsorted(arr, 11, side="right")

print(x)

6


The method starts the search from the right and returns the first index where the number 11 is no longer less than the next value.

Find the indexes where [2, 4, 6] should be inserted in the array. 

In [9]:
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]
