#### Shape of an Array 

The shape of an array is the number of elements in each dimensions. 

In [2]:
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print("shape of the array: ", arr.shape)

shape of the array:  (2, 4)


The example of above returns (2, 4), which means that the array has 2 dimensions, where the first dimension has 2 elements and the second has 4. 

Create an array with 5 dimensions using ndim using a vector with values 1, 2, 3, 4 and verify that last dimension has value 4. 

In [3]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print("shape of array: ", arr.shape)

[[[[[1 2 3 4]]]]]
shape of array:  (1, 1, 1, 1, 4)


In the shape of of above tuple we can see that there is 4 , 1's and in the index value 4 we get see the value 4 meaning that it has dimension 4. 

#### Reshaping Arrays 

Reshaping means changing the shape of the array. The shape of an array is the number of elements in each dimensions. By reshaping we can change the number of elements in each dimension. 

In [5]:
# Convert the following 1-D array with 12 elements into a 2-D array. 
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print("Before reshaping the array: ", arr.shape)
newarr = arr.reshape(4, 3)
print("After shaping the array: ", newarr.shape)
print(newarr)

Before reshaping the array:  (12,)
After shaping the array:  (4, 3)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


What happens if there is few elements only present which will be insufficient to reshape the new array. 

In [6]:
arr = np.array([1, 2, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print("Before reshaping the array: ", arr.shape)
newarr = arr.reshape(4, 3)
print("After shaping the array: ", newarr.shape)
print(newarr)

Before reshaping the array:  (11,)


ValueError: cannot reshape array of size 11 into shape (4,3)

# Reshape From 1-D to 3-D 
Convert the following 1-D array with 12 elements into a 3-D array. The outermost dimension will have 2 arrays that contains 3 arrays with each 3 elements. 

In [8]:
arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr1.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# Can We Reshape into any shape ? 
Yes we can reshape array into any shape. for example 8 elements of 1D array can be converted into 2D array as (2*4) but we cannot convert it into 3D array because that would require 3x3 = 9 elements. 

In [10]:
arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr1.reshape(2, 4)
print("After reshaped array to 2D array: ", newarr)
print("Trying to reshape array : ", arr1.reshape(2, 3))

After reshaped array to 2D array:  [[1 2 3 4]
 [5 6 7 8]]


ValueError: cannot reshape array of size 8 into shape (2,3)

# Returns Copy or View ?
check if the returned array is a copy or view ? 

In [13]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 4)
print(arr.reshape(2, 4).base)
print(newarr)

# we found that the reshaping the array is the view. 

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]


# Flattening the arrays 
Flattening array means converting a multidimensionsional array into a 1D array. 
we can use reshape(-1) to do this. 

In [14]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


# Unknown dimension 
you are allowed to have one unknown dimesion. Meaning that you do not have to specify exact number for one of the dimension in the reshape method. 

Pass -1 as the value, and NumPy will calculate this number for you.

In [15]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [3]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 2, -1)
print(newarr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(6)
print(newarr)

[1 2 3 4 5 6]
