# Importing Necessary Arrays

In [1]:
import numpy as np 

In [6]:
arr = np.array([[1, 2, 3, 4], [5, np.nan, 6, np.nan]])

print("dimension of the array : ", arr.ndim)

print("accessing first row of the array: ", arr[0])

print("accessing second row of the array: ", arr[1])

print("slicing the array row 1 col 3: ", arr[0][3])

print("Note: array indexing always starts from 0, ")

dimension of the array :  2
accessing first row of the array:  [1. 2. 3. 4.]
accessing second row of the array:  [ 5. nan  6. nan]
slicing the array row 1 col 3:  4.0
Note: array indexing always starts from 0, 


In [8]:
# Iterating the arrays

for i in arr:
    for j in i:
        print(j)

1.0
2.0
3.0
4.0
5.0
nan
6.0
nan


In [9]:
print("shape of the array: ", arr.shape)

shape of the array:  (2, 4)


In [12]:
arr_3D = np.array([[[1, 2, 4], [5, 6, 7], [8, 9, 10]], [[1.1, 1.2, 1.3], [4, 5, 6], [7, 8, 9]]])

print("shape of the 3D array: ", arr_3D.shape)

print("3-D array: ", arr_3D)

shape of the 3D array:  (2, 3, 3)
3-D array:  [[[ 1.   2.   4. ]
  [ 5.   6.   7. ]
  [ 8.   9.  10. ]]

 [[ 1.1  1.2  1.3]
  [ 4.   5.   6. ]
  [ 7.   8.   9. ]]]


In [16]:
print("reshaping or Flattening array: ", arr_3D.reshape(-1))

reshaping or Flattening array:  [ 1.   2.   4.   5.   6.   7.   8.   9.  10.   1.1  1.2  1.3  4.   5.
  6.   7.   8.   9. ]


since there are 18 elements in the array, 
it we can only reshape in the multiple of the 18 meaning that:

3 * 3 * 2 = 18 

In [20]:
newarr = arr_3D.reshape(3, 3, -1)
print("After reshaping the array: ", newarr)
print("first reshaping means that 3 row, 3 row and remaining can be anything")
newarr = arr_3D.reshape(2, 3, -1)
print("After reshaping array: ", newarr)

After reshaping the array:  [[[ 1.   2. ]
  [ 4.   5. ]
  [ 6.   7. ]]

 [[ 8.   9. ]
  [10.   1.1]
  [ 1.2  1.3]]

 [[ 4.   5. ]
  [ 6.   7. ]
  [ 8.   9. ]]]
first reshaping means that 3 row, 3 row and remaining can be anything
After reshaping array:  [[[ 1.   2.   4. ]
  [ 5.   6.   7. ]
  [ 8.   9.  10. ]]

 [[ 1.1  1.2  1.3]
  [ 4.   5.   6. ]
  [ 7.   8.   9. ]]]


In [23]:
# NOTE: If there are exactly 8 elements 4, 4 elements in each 2d array then 
# We can reshape with 8 but flattening is most used. 
newarr = arr.reshape(8)
print(newarr)

[ 1.  2.  3.  4.  5. nan  6. nan]


In [24]:
for index, element in enumerate(arr_3D):
    print(index, element)

0 [[ 1.  2.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]
1 [[1.1 1.2 1.3]
 [4.  5.  6. ]
 [7.  8.  9. ]]


In [27]:
for index, element in enumerate(newarr):
    print(index, element)

0 1.0
1 2.0
2 3.0
3 4.0
4 5.0
5 nan
6 6.0
7 nan


In [32]:
for index, element in np.ndenumerate(arr_3D):
    print(index, element)
    print(index[0], index[0], index[0])

(0, 0, 0) 1.0
0 0 0
(0, 0, 1) 2.0
0 0 0
(0, 0, 2) 4.0
0 0 0
(0, 1, 0) 5.0
0 0 0
(0, 1, 1) 6.0
0 0 0
(0, 1, 2) 7.0
0 0 0
(0, 2, 0) 8.0
0 0 0
(0, 2, 1) 9.0
0 0 0
(0, 2, 2) 10.0
0 0 0
(1, 0, 0) 1.1
1 1 1
(1, 0, 1) 1.2
1 1 1
(1, 0, 2) 1.3
1 1 1
(1, 1, 0) 4.0
1 1 1
(1, 1, 1) 5.0
1 1 1
(1, 1, 2) 6.0
1 1 1
(1, 2, 0) 7.0
1 1 1
(1, 2, 1) 8.0
1 1 1
(1, 2, 2) 9.0
1 1 1


In [31]:
for element in np.nditer(arr_3D):
    print(element)

1.0
2.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0
1.1
1.2
1.3
4.0
5.0
6.0
7.0
8.0
9.0


# Concatenating the array

In [33]:
arr1 = [1, 2, 3]
arr2 = [3, 4, 5]
print(np.concatenate(arr1, arr2))

TypeError: 'list' object cannot be interpreted as an integer

In [37]:
arr1 = np.array([1, 2, 4])
arr2 = np.array([5, 6, 7])

newarr = np.concatenate((arr1, arr2))
print("After concatenating the array: ", newarr)

After concatenating the array:  [1 2 4 5 6 7]


In [38]:
newarr = np.stack((arr1, arr2))
print(newarr)

[[1 2 4]
 [5 6 7]]


In [39]:
newarr = np.vstack((arr1, arr2))
print(newarr)

[[1 2 4]
 [5 6 7]]


In [40]:
newarr = np.hstack((arr1, arr2))
print(newarr)

[1 2 4 5 6 7]


In [41]:
newarr = np.dstack((arr1, arr2))
print(newarr)

[[[1 5]
  [2 6]
  [4 7]]]


In [42]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[11, 12, 13], [14, 15, 16]])
newarr = np.stack((arr1, arr2))
print(newarr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [14 15 16]]]


In [43]:
newarr_vstack = np.vstack((arr1, arr2))
print(newarr_vstack)

[[ 1  2  3]
 [ 4  5  6]
 [11 12 13]
 [14 15 16]]


In [45]:
newarr_hstack = np.hstack((arr1, arr2))
print(newarr_hstack)    # [1 2 3 11 12 13]

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]]


In [48]:
print(arr1, " \n", arr2)

[[1 2 3]
 [4 5 6]]  
 [[11 12 13]
 [14 15 16]]


In [46]:
newarr_dstack = np.dstack((arr1, arr2))
print(newarr_dstack)

[[[ 1 11]
  [ 2 12]
  [ 3 13]]

 [[ 4 14]
  [ 5 15]
  [ 6 16]]]


In [50]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
newarr = np.array_split(arr, 4)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6]]), array([[7, 8]]), array([[ 9, 10]])]


In [52]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

mask_even_array = np.where(arr % 2 == 0)

print(mask_even_array)

(array([1, 3, 5, 7, 9], dtype=int64),)


In [54]:
mask_odd = np.where(arr % 2 == 1)

print(mask_odd)

print("Note: it returns the array index")

(array([0, 2, 4, 6, 8], dtype=int64),)
Note: it returns the array index


In [56]:
newarr = np.searchsorted(arr, 4)

print(newarr)
print("it means that the element = 4 need to be inserted at the index 3 to maintain sorted order")

3
it means that the element = 4 need to be inserted at the index 3 to maintain sorted order


In [4]:
import numpy as np
arr = np.array([2, -1, 0, 5])
newarr = np.sort(arr)
print("sorted array: ", newarr)

sorted array:  [-1  0  2  5]


In [ ]:
masking_array = arr[True, False, True, False]
print("Filtering array: ", masking_array)

Filtering array:  []


In [6]:
masking_array = arr[[True, False, True, False]]
print("Filtering array: ", masking_array)

Filtering array:  [2 0]
