# Object 
## Create a numpy ndarray object. 
        A array created by numpy is also called ndarray. we can use 
`````
np.array() 
`````
        builtin function to create an ndarray. To create an array we can use any object like list, array, tuple and dictionary. 

In [2]:
import numpy as np 

In [6]:
arr1 = np.array(43)
print("example of array: ", arr1)
print("type of arrray: ", type(arr1))

example of array:  43
type of arrray:  <class 'numpy.ndarray'>


In [7]:
tup_arr = np.array((1, 2, np.nan, 3, np.nan, 5))
print("Example of tuple : ", tup_arr)
arr = np.array([1, 2, 3, 4, 5, np.nan])
print("Example of array: ", arr)

Example of tuple :  [ 1.  2. nan  3. nan  5.]
Example of array:  [ 1.  2.  3.  4.  5. nan]


In [18]:
# 0 dimension array 
dim_0Arr = np.array(23)
print("0 dim array example : ", dim_0Arr)
dim_1Arr = np.array([1, 2, 3, np.nan, 4])
print("1 dim array example : ", dim_1Arr)
dim_2Arr = np.array([[1, 2, 3], ['shiva', 'anje', 'krisha']])
print("2 dim array exmaple: ", dim_2Arr)
dim_3Arr = np.array([[[1, 2, 3], [4, 5, 6], [7, 68, 9]], [[4, np.nan, 5], [5, 0.0, 0.0], [0, 0, 0]]])
print("3 dim array example : ", dim_3Arr)
higher_dim = np.array(45, ndmin=5)


0 dim array example :  23
1 dim array example :  [ 1.  2.  3. nan  4.]
2 dim array exmaple:  [['1' '2' '3']
 ['shiva' 'anje' 'krisha']]
3 dim array example :  [[[ 1.  2.  3.]
  [ 4.  5.  6.]
  [ 7. 68.  9.]]

 [[ 4. nan  5.]
  [ 5.  0.  0.]
  [ 0.  0.  0.]]]


In [23]:
print("dim 0 array : ", dim_0Arr.ndim)
print("dim 1 array : ", dim_1Arr.ndim)
print("dim 2 array : ", dim_2Arr.ndim)
print("dim 3 array : ", dim_3Arr.ndim)
print("higher dim array : ", higher_dim, ", dim: ", higher_dim.ndim)

dim 0 array :  0
dim 1 array :  1
dim 2 array :  2
dim 3 array :  3
higher dim array :  [[[[[45]]]]] , dim:  5


In this array the innermost dimension (5th dim) has 1 elements, the 4th dim has 1 element that is the 5 dim vector, the 3rd dim has 1 element that is the matrix with the 4 dim vector, the 2nd dim has 1 element that is 3D array and 1st dim has 1 element that is a 4D array.