# Iterating through Arrays 

Iterating through arrays means accessing elements one by one in array. 

As we also have to deal with the multi dimensional array. we can simply use for loop. 

In [1]:
import numpy as np 

In [2]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
for i in arr:
    print(i)

1
2
3
4
5
6
7
8
9
10


#### Iterating through Multi dimensional Arrays 
In a 2-D array it will go through all the rows. 

In [4]:
arr = np.array([[1, 2, 4], [5, 6, 7]])
for i in arr:
    print(i)

[1 2 4]
[5 6 7]


if we iterate on n-D array it will iterate through n-1th dimension one first and will go iterating n-nth dimension. 

#### Iterating through 3-D arrays 

In [6]:
arr = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 14], [15, 16, 17]]])
for i in arr:
    print(i)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 14]
 [15 16 17]]


In [10]:
for i in arr:
    print(i)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 14]
 [15 16 17]]


In [ ]:
for i in arr:
    for j in i: 
        for k in j:
            print(i)

In [ ]:
# iterating on each scalar element Using nditer() we use nditer 
# because 

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
14
15
16
17


#### Iterating Array with Different Data Types 

we can use op_dtypes argument and pass it the expected datatype to change the datatype of elements while iterating. 

In [12]:
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
    print(x)
    print(x.dtype)

b'1'
|S11
b'2'
|S11
b'3'
|S11
b'4'
|S11
b'5'
|S11
b'6'
|S11
b'7'
|S11
b'8'
|S11
b'9'
|S11
b'10'
|S11
b'11'
|S11
b'12'
|S11
b'13'
|S11
b'14'
|S11
b'14'
|S11
b'15'
|S11
b'16'
|S11
b'17'
|S11


In [13]:
## Iterating with different step size 
# we can use filtering and followed by iteration. 
arr = np.array([[1, 2, 3, 4, 5, 6], [1, 2, 3, 4, 5, 6]])
for x in np.nditer(arr[:, ::2]):
    print(x)

1
3
5
1
3
5


## Enumerated Iteration Using ndenumerate() 
sometimes we require mapping index of the element while iterating ,
the ndenumerate() method can be used for those used cases. 

In [14]:
arr = np.array([1, 2, 3])
for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [17]:
arr_2D = np.array([[1, 2, 3], [4, 5, 6]])
for idx, x in np.ndenumerate(arr_2D):
    print(idx[0], idx[1], x)

0 0 1
0 1 2
0 2 3
1 0 4
1 1 5
1 2 6
