# Random Data Distribution 
## What is Data Distribution ? 
- Data distribution is a list of all possible values in terms of probablites and how often each value occurs. 
- such list are important when working with statistics and data science. 


It returns randomly generated data distributions. 

## Random Distribution
A random distribution is a set of random numbers that follow a certain probability density function. 

## Probability Density Function: 
A function that describes a continuous probability, i.e. probabilities of all values in an array. 

we generate random numbers based on defined probabilities using the <span style="color:red">choice()</span> method of the random module. 

The probability is set by a number between 0 and 1 where, 0 means the value will never occur and 1 means the value will always occur.

Generate a 1-D array containing 100 values, where each value has to be 3, 5, 7, 9. 

### Example:

The probability for the value 3 = 0.1 

The probability for the value 7 = 0.8 

The probability for the value 5 = 0

The probability for the value 9 = 0

In [2]:
from numpy import random 

x = random.choice([3, 5, 7, 9], p=[0.2, 0.8, 0.0, 0.0], size=(100))

print(x)

[5 5 5 5 5 3 5 5 5 5 5 3 5 5 5 3 5 3 5 5 5 5 5 5 3 5 5 5 3 5 5 5 5 3 3 5 5
 5 5 5 3 5 5 5 5 5 5 5 5 5 5 5 5 5 3 5 5 5 3 5 3 5 5 3 3 5 3 5 5 3 5 5 5 3
 5 5 5 5 5 5 5 5 5 3 5 5 5 5 3 5 5 5 3 5 3 5 5 3 3 5]


In [3]:
from numpy import random

x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3, 5))

print(x)

[[7 7 5 5 7]
 [5 7 7 7 7]
 [5 7 5 5 3]]
