In [2]:
import numpy as np 

In [5]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6 7]


In [7]:
arr1 = np.array([[1, 2], [3, 5]])
arr2 = np.array([[3, 4], [5, 7]])
arr = np.hstack((arr1, arr2)) # 0 means column
print(arr)

[[1 2 3 4]
 [3 5 5 7]]


In [ ]:
arr = np.vstack((arr1, arr2))
print("vertical stack", arr)   # Vertical stack

vertical stack [[1 2]
 [3 5]
 [3 4]
 [5 7]]


In [11]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([2, 3, 4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 2 3 4 5 6]


In [ ]:
arr1 = np.array([[2, 3, 4], [5, 6, 7]])
arr2 = np.array([[0.3, 0.5, 0.6], [1.1, 2.3, 4.4]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr1)
print(arr2)
print("---------------------------------------------")
print(arr) 

[[2 3 4]
 [5 6 7]]
[[0.3 0.5 0.6]
 [1.1 2.3 4.4]]
---------------------------------------------
[[2.  3.  4.  0.3 0.5 0.6]
 [5.  6.  7.  1.1 2.3 4.4]]


In [16]:
arr = np.concatenate((arr1, arr2), axis=0)
print(arr)


[[2.  3.  4. ]
 [5.  6.  7. ]
 [0.3 0.5 0.6]
 [1.1 2.3 4.4]]
