#### Importing necessary Libraries 

In [2]:
import numpy as np 

#### Concatenating Array
let assume that,

 arr1 has [a1, b1, c1] and arr2 has [a2, b2, c2]

if we concatenate then, concatenated array becomes, 

concated_arr = [a1, b1, c1, a2, b2, c2]

In [4]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6 7]


#### Stacking Along horizontal 
let assume that,

arr1 has [a1, b1, c1] and arr2 has [a2, b2, c2]

if we do hstack, horizontally stack , then array becomes, 
arr = [a1, b1, c1, a2, b2, c2]

In [5]:
arr = np.hstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6 7]


what if array is 2-D ? 

arr1 has [[a1, b1], [c1, d1]]

arr2 has [[a2, b2], [c2, d2]]

if we do hstack in 2-D array. then, 

array becomes, 

arr = [[a1, b1, a2, b2], [c1, d1, c2, d2]]

In [6]:
arr1 = np.array([[1, 2], [3, 5]])
arr2 = np.array([[3, 4], [5, 7]])
arr = np.hstack((arr1, arr2))
print(arr)

[[1 2 3 4]
 [3 5 5 7]]


what if array is 2-D ? 

arr1 has [[a1, b1], [c1, d1]]

arr2 has [[a2, b2], [c2, d2]]

if we do vstack in 2-D array. then, 

array becomes, 

arr = [[a1, b1], [c1, d1], [a2, b2], [c2, d2]]

In [7]:
arr = np.vstack((arr1, arr2))
print("vertical stack", arr)   # Vertical stack

vertical stack [[1 2]
 [3 5]
 [3 4]
 [5 7]]


In [8]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([2, 3, 4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 2 3 4 5 6]


what if array is 2-D in concatenation? 

arr1 has [[a1, b1], [c1, d1]]

arr2 has [[a2, b2, c2], [d2, e2, f2]]

if we do concatenation in 2-D array. then, 

array becomes, 

arr = [[a1, b1, a2, b2, c2], [c1, d1, d2, e2, f2]]

In [13]:
arr1 = np.array([[2, 3, 4], [5, 6, 7]])
arr2 = np.array([[0.3, 0.5, 0.3], [1.1, 2.3, 1.4]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr1)
print(arr2)
print("---------------------------------------------")
print(arr) 

[[2 3 4]
 [5 6 7]]
[[0.3 0.5 0.3]
 [1.1 2.3 1.4]]
---------------------------------------------
[[2.  3.  4.  0.3 0.5 0.3]
 [5.  6.  7.  1.1 2.3 1.4]]


what if array is 2-D in concatenation? 

arr1 has [[a1, b1], [c1, d1]]

arr2 has [[a2, b2, c2], [d2, e2, f2]]

if we do concatenation in 2-D array. then, 

array becomes, 

arr = [[a1, b1], [c1, d1],  [a2, b2, c2], [d2, e2, f2]]

In [14]:
arr = np.concatenate((arr1, arr2), axis=0)
print(arr)

[[2.  3.  4. ]
 [5.  6.  7. ]
 [0.3 0.5 0.3]
 [1.1 2.3 1.4]]
