#### NumPy Joining Array

Joining means putting contents of two or more arrays in a single array. In SQL we join 
tables based on a key, wheras in NumPy we join arrays by axes. 

We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis, if axis is not explicity passed, it is taken as 0.. 

In [1]:
import numpy as np 

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [2]:
##### Example: 

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
arr3 = np.concatenate((arr1, arr2), axis=0)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [3]:
print(arr3)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### Joining Arrays Using Stack Functions
Stacking is same as concatenation, the only difference is that stacking is done along a new axis. 

In [4]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)
arr3 = np.stack((arr1, arr2), axis=0)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [5]:
print(arr3)

[[1 2 3]
 [4 5 6]]


### Stacking Along Rows
NumPy provides a helper function: hstack() to stack along rows.

In [6]:
arr = np.hstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


#### Stacking Along Columns
NumPy provides a helper functions: vstack() to stack along columns. 


In [7]:
arr = np.vstack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


#### Stacking Along Height (depth)
NumPy provides a helper functions dstack() to stack height, which is the same as depth

In [8]:
arr = np.dstack((arr1, arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [9]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 7], [6, 4]])

print("normal stacking: ", np.stack((arr1, arr2)))
print()
print("vertical stacking: ", np.vstack((arr1, arr2)))
print()
print("horizontal stacking: ", np.hstack((arr1, arr2)))
print()
print("depth stacking: ", np.dstack((arr1, arr2)))

normal stacking:  [[[1 2]
  [3 4]]

 [[5 7]
  [6 4]]]

vertical stacking:  [[1 2]
 [3 4]
 [5 7]
 [6 4]]

horizontal stacking:  [[1 2 5 7]
 [3 4 6 4]]

depth stacking:  [[[1 5]
  [2 7]]

 [[3 6]
  [4 4]]]
