# Random Numbers in NumPy 

What is a Random Number?

Random Number does not mean different number every time. Random means something that can no be predicted logically. 

Pseudo Random and True Random 

The random number generated through any type of algorithm is called Pseudo Random. It means If there is a program to generate random number then, it can be predicted, thus it is not truly random number as well.

Then how to make a True Random number ? 
Yes, In order to generate a True Random number our computer might need to get the data from the outer sources. This outer resources data is generallu keystrokes, mouse movements, data on network etc. 

In this NoteBook we will use pseudo random numbers. 
# Generate Random Number
NumPY offers the random module to work with random numbers

In [1]:
from numpy import random 

Generate a random integer from 0 to 100

In [3]:
x = random.randint(100)

print(x)

39


To Generate a random integer we use random.randint() but to generate a float value we use random.rand()

In [4]:
x = random.rand()

print(x)

0.3730591010436637


# generate a 1-D array containing 5 random integers from 0 to 100

In [13]:
x = random.randint(100, size=(5))

print(x)

[55  5 45  6 77]


# Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100

In [14]:
x = random.randint(100, size=(3, 5))

print(x)

[[49 55  7 74 19]
 [73  5 67 58  3]
 [78 54 18 56 17]]


# Generate a 1-D array of random float. 

In [8]:
x = random.rand(5)

print(x)

[0.73104688 0.03513227 0.90495382 0.75935607 0.24412441]


# Generate a 2-D array with 3 rows, each row containin 5 random Float Numbers

In [15]:
x = random.rand(3, 5)

print(x)

[[0.94332211 0.49846837 0.68611974 0.2644582  0.93235971]
 [0.40323862 0.99414471 0.75328548 0.16879672 0.86870516]
 [0.32896509 0.30896495 0.90021547 0.12634242 0.22763557]]


# Generate Random Number From Array 

The choice() method allows to choose one value from the given array. 

The choice() method takes an array as a parameter and randomly returns one of the values. 

In [10]:
x = random.choice([3, 4, 9, 10])

print(x)

9


The <span style="color:red">choice()</span> method also allows you to return an array of values . 

Add a size parameter to specify the shape of the array. 

In [12]:
x = random.choice([3, 9, 1, 10], size=(3, 5))

print(x)

[[ 9 10  1  1  9]
 [10  1  3 10  3]
 [ 9  9  1  1 10]]
